### ISSUE TITLE
Rest Api - Pagination for rest json responses that have the potential to be very long

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#158]
#### Pagination

For responses that need it - pagination could be something like this:

```
GET v1/address/[address]?page=1&per_page=20
```

* default page = last page
* default per page = 20

##### Metadata

It is helpful to have medatdata for pagination:

```
GET api/transactions/address/[address]?page=1&per_page=20&metadata=true
```

* default metadata = false

A response with metadata (with semantic web style links):

```json
{"metadata":{
  "page": 2,
  "per_page": 20,
  "page_count": 20,
  "total_count": 200,
  "links": [
    {"current": "api/transactions/address/[address]?page=2&per_page=20"},
    {"first": "api/transactions/address/[address]?page=0&per_page=20"}
    {"prev": "api/transactions/address/[address]?page=1&per_page=20"}
    {"next": "api/transactions/address/[address]?page=3&per_page=20"}
    {"last": "api/transactions/address/[address]?page=10&per_page=20"}
  ]
},
"transactions": []
}
```

**Comment by tbrand** [comment]
I don't understand the metadata's real use cases.
Also, getting the `total_count` is worth for the performance since the node have to get all transactions once. (and the transactions out of the range will be dropped)

For short, the implementation will not the lazy evaluation. And without the `total_count`, the metadata means nothing I think. (Frontend can handle the pagination, he knows the next page and prev page.)

What do you think?

**Comment by kingsleyh** [comment]
Ok that’s fine :)

**Comment by tbrand** [comment]
Thanks, then I will open the Pull Request.
