### ISSUE TITLE
Do not hold the entire chain in memory in the node

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#258]
Find a solution so that we don't hold the entire chain in memory in the node

**Comment by jferas** [comment]
The first step in this effort will be to no longer store the meaningful data of a block in the Block table as a JSON string, but to break out the individual elements into fields/columns of the Block table.  This is necessary so that the operations that today read the entire chain by scanning the array in memory can achieve similar functionality with a `select` operation in SQL.

The following elements will become fields (copied from `block.cr`):
      index:            Int64,
      nonce:            UInt64,
      prev_hash:        String,
      merkle_tree_root: String,
      timestamp:        Int64,
      difficulty:  Int32,

Note that `transactions` are not listed above.  Transactions will be normalized out into their own table, since an array of transactions reside in a block.  In addition to the fields listed below, the Transaction table will have a `block_id` field linking an individual transaction back to an individual block in the Block table. Here are the remaining fields of a transaction that will be stored in the transaction table (copied from `transaction.cr`):
      id: String,
      action: String,
      message: String,
      token: String,
      prev_hash: String,
      timestamp: Int64,
      scaled: Int32,

Note that `senders` and `recipients` are not listed above.  They will be normalized out into their own tables, since arrays of senders and recipients reside in a transaction.  The Sender and Recipient tables will in turn have a `transaction_id` that links an individual back to an individual transaction.

The fields of the Sender table (copied from `models.cr`):
    address: String,
    public_key: String,
    amount: Int64,
    fee: Int64,
    sign_r: String,
    sign_s: String,

The fields of the Recipient table (copied from `models.cr`):
    address: String,
    amount: Int64,

**Comment by kingsleyh** [comment]
done
