### ISSUE TITLE
Fast block error when syncing from testnet

### ISSUE THREAD

**Issue by kingsleyh** [SushiChain/SushiChain#316]
When starting up a new node against the testnet - the first attempt to sync failed with a fast block error. Then I tried again with whatever it had managed to write to the local db and it synced the rest of the chain ok.

The fast blocks should be synced last - after all the slow blocks have been synced. So this should not have happened.

```
[ 2019-10-02 23:03:25 --    Info ] highest fast block index: 0
[ 2019-10-02 23:03:25 --    Info ] start synching chain
[ 2019-10-02 23:03:27 --    Info ] received 1158 SLOW blocks
[ 2019-10-02 23:03:27 --    Info ] received 1 FAST blocks
[ 2019-10-02 23:03:44 --    Erro ] found invalid slow block while syncing blocks
[ 2019-10-02 23:03:44 --    Erro ] the reason:
[ 2019-10-02 23:03:44 --    Erro ] Unable to send 0.00001234 SUSHI to recipient because you do not have enough SUSHI. You currently have: 0 SUSHI and you are receiving: 0 SUSHI from senders,  giving a total of: 0 SUSHI
[ 2019-10-02 23:03:44 --    Erro ] found invalid fast block while syncing blocks
[ 2019-10-02 23:03:44 --    Erro ] the reason:
[ 2019-10-02 23:03:44 --    Erro ] Unable to send 0.00001234 SUSHI to recipient because you do not have enough SUSHI. You currently have: 0 SUSHI and you are receiving: 0 SUSHI from senders,  giving a total of: 0 SUSHI
```

**Comment by kingsleyh** [comment]
It looks like the SLOW block was invalid but then it continued to sync fast. We should not continue to sync if there was a failure. Also we should not ever get into a situation where an invalid block can be coming from the parent node during a sync.

**Comment by jferas** [comment]
Chased it down.. it is actually more related to the fact that the UTXO "record" method is scanning the DB, not the in-memory chain to build its indices and internal storage.. but since the advent of fast/slow blocks, the "replace_chain" method doesn't put data into the database until after both chains have been validated and sorted.  This is why it fails on the first run (with an empty DB) then it succeeds on the second run (the DB is present, so the UTXO record method properly builds its storage).  I've got a fix in place and working.. we don't wait .. we put the new block in the DB as soon as we realize it is valid (in "replace_slow_chain" and "replace_fast_chain" we call a new database method "replace_block").... BUT NOW THAT I THINK ABOUT IT I DON"T LIKE THIS SOLUTION.. because it means that we're writing to the DB before we've validated both chains....so I need to think about it some more.. but that is the root cause.. I just don't like my current solution.. pulled the trigger too quickly on the fix.
